Refactored user and order to change how order is handled. Also added …
tvtusc25/Group-Sprint-1-Bookazon pull request #26
Opened 2024-09-29 18:09 UTC by ryanmogauro

I changed order.java to handle most of the checkout process. Now, user.checkout() takes in an order object, calls its checkout method, and adds it to the orders list. I also had to create some helper methods, getCart and getSubscriptionObject, for creating order objects in Bookazon.java.

2024-09-29 21:26 UTC, ehburdick commented on src/Order.java
> +        this.setDateCreated("2024-01-01");
Should this be dataCreated?

2024-09-29 21:27 UTC, ehburdick requested changes
Everything looked good, except, I feel as if setDateCreated should be dataCreated, may be out of the scope of the issue though

2024-09-30 15:42 UTC, ryanmogauro commented
Just changed dateCreated and dateShipped to type LocalDate (previously String). The checkout method now sets dateCreated to LocalDate.now(), instead of the previously hard-coded date.

2024-09-30 17:00 UTC, ehburdick approved these changes
Looks good, glad Date is not a magic value anymore

2024-09-30 17:00 UTC, merged